"""add contract fields to product_supplier

Revision ID: 3a0e75bb796f
Revises: 527ddf09e651
Create Date: 2026-06-04 14:41:44.460003

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3a0e75bb796f'
down_revision: Union[str, Sequence[str], None] = '527ddf09e651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_status', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('term_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('term_end', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('annual_budget', sa.Numeric(precision=14, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_supplier', schema=None) as batch_op:
        batch_op.drop_column('annual_budget')
        batch_op.drop_column('term_end')
        batch_op.drop_column('term_start')
        batch_op.drop_column('contract_status')

    # ### end Alembic commands ###
