"""add TCO layers (landed, deployment, opex, eol, recovery)

Revision ID: 75e1335a36a9
Revises: cbcfb8ce5765
Create Date: 2026-06-07 21:24:09.380072

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '75e1335a36a9'
down_revision: Union[str, Sequence[str], None] = 'cbcfb8ce5765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_cost',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('task', sa.Enum('RECEIVING', 'RACKING', 'CABLING', 'IMAGING', name='deploymenttask'), nullable=False),
    sa.Column('labor_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('incurred_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployment_cost', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployment_cost_asset_id'), ['asset_id'], unique=False)

    op.create_table('eol_cost',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('decommission', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data_destruction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('weee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('itad_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('eol_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eol_cost', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eol_cost_asset_id'), ['asset_id'], unique=True)

    op.create_table('landed_cost',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('cost_type', sa.Enum('FREIGHT', 'INSURANCE', 'DUTY', 'HANDLING', name='landedcosttype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('incoterm', sa.String(length=8), nullable=True),
    sa.Column('incurred_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('landed_cost', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_landed_cost_asset_id'), ['asset_id'], unique=False)

    op.create_table('opex_ledger',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('power_kwh', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pue', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('energy_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('cooling', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('maintenance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('license', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opex_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opex_ledger_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opex_ledger_period'), ['period'], unique=False)

    op.create_table('recovery_value',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('residual_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('resale_channel', sa.String(length=64), nullable=True),
    sa.Column('depr_method', sa.Enum('STRAIGHT_LINE', 'DECLINING', 'NONE', name='depreciationmethod'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('recovery_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_value', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_value_asset_id'), ['asset_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recovery_value', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_value_asset_id'))

    op.drop_table('recovery_value')
    with op.batch_alter_table('opex_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opex_ledger_period'))
        batch_op.drop_index(batch_op.f('ix_opex_ledger_asset_id'))

    op.drop_table('opex_ledger')
    with op.batch_alter_table('landed_cost', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_landed_cost_asset_id'))

    op.drop_table('landed_cost')
    with op.batch_alter_table('eol_cost', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eol_cost_asset_id'))

    op.drop_table('eol_cost')
    with op.batch_alter_table('deployment_cost', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployment_cost_asset_id'))

    op.drop_table('deployment_cost')
    # ### end Alembic commands ###
