"""add asset_event lifecycle log

Revision ID: 93c2241593e7
Revises: c5707dc49823
Create Date: 2026-06-02 07:02:15.258496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c2241593e7'
down_revision: Union[str, Sequence[str], None] = 'c5707dc49823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_event',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('RECEIVED', 'MOVED', 'STATUS_CHANGED', name='asseteventtype'), nullable=False),
    sa.Column('from_status', sa.Enum('RECEIVED', 'IN_STORAGE', 'DEPLOYED', 'MAINTENANCE', 'DECOMMISSIONED', 'DISPOSED', name='assetstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('RECEIVED', 'IN_STORAGE', 'DEPLOYED', 'MAINTENANCE', 'DECOMMISSIONED', 'DISPOSED', name='assetstatus'), nullable=True),
    sa.Column('from_location_id', sa.String(length=36), nullable=True),
    sa.Column('to_location_id', sa.String(length=36), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['from_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_event_asset_id'), ['asset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_event_asset_id'))

    op.drop_table('asset_event')
    # ### end Alembic commands ###
