"""add purchase requisition + feedback tables

Revision ID: a797f3c40de6
Revises: ec0024f4ffd0
Create Date: 2026-06-06 11:58:04.965291

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a797f3c40de6'
down_revision: Union[str, Sequence[str], None] = 'ec0024f4ffd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_requisition',
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('STAGED', 'PLACED', 'REJECTED', name='requisitionstatus'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_floor', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('auto_placed', sa.Boolean(), nullable=False),
    sa.Column('po_id', sa.String(length=36), nullable=True),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('order_by', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_requisition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_requisition_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_requisition_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('requisition_feedback',
    sa.Column('requisition_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('proposed_qty', sa.Integer(), nullable=False),
    sa.Column('final_qty', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('auto_placed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['purchase_requisition.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requisition_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requisition_feedback_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_requisition_feedback_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requisition_feedback_requisition_id'), ['requisition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requisition_feedback_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('requisition_line',
    sa.Column('requisition_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('product_supplier_id', sa.String(length=36), nullable=True),
    sa.Column('proposed_qty', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=True),
    sa.Column('line_confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['product_supplier_id'], ['product_supplier.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['purchase_requisition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requisition_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requisition_line_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requisition_line_requisition_id'), ['requisition_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisition_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requisition_line_requisition_id'))
        batch_op.drop_index(batch_op.f('ix_requisition_line_product_id'))

    op.drop_table('requisition_line')
    with op.batch_alter_table('requisition_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requisition_feedback_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_requisition_feedback_requisition_id'))
        batch_op.drop_index(batch_op.f('ix_requisition_feedback_product_id'))
        batch_op.drop_index(batch_op.f('ix_requisition_feedback_action'))

    op.drop_table('requisition_feedback')
    with op.batch_alter_table('purchase_requisition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_requisition_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_requisition_status'))

    op.drop_table('purchase_requisition')
    # ### end Alembic commands ###
