"""add tracking logistics schema

Revision ID: c44cb7b1ba0b
Revises: 3a0e75bb796f
Create Date: 2026-06-04 14:46:17.078951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c44cb7b1ba0b'
down_revision: Union[str, Sequence[str], None] = '3a0e75bb796f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trk_supplier',
    sa.Column('supplier_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('payment_terms', sa.String(length=16), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_table('trk_purchase_order',
    sa.Column('po_id', sa.String(length=32), nullable=False),
    sa.Column('supplier_id', sa.String(length=32), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('expected_delivery', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['trk_supplier.supplier_id'], ),
    sa.PrimaryKeyConstraint('po_id')
    )
    with op.batch_alter_table('trk_purchase_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trk_purchase_order_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('trk_shipment',
    sa.Column('shipment_id', sa.String(length=32), nullable=False),
    sa.Column('po_id', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('carrier', sa.String(length=64), nullable=True),
    sa.Column('current_status', sa.String(length=24), nullable=False),
    sa.Column('progress_idx', sa.Integer(), nullable=False),
    sa.Column('current_location', sa.String(length=128), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('last_event_at', sa.DateTime(), nullable=True),
    sa.Column('eta_original', sa.Date(), nullable=True),
    sa.Column('eta_current', sa.Date(), nullable=True),
    sa.Column('exception_flag', sa.Boolean(), nullable=False),
    sa.Column('exception_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['trk_purchase_order.po_id'], ),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    with op.batch_alter_table('trk_shipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trk_shipment_po_id'), ['po_id'], unique=False)

    op.create_table('trk_shipment_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('location_name', sa.String(length=128), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('event_ts', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['trk_shipment.shipment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trk_shipment_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trk_shipment_event_shipment_id'), ['shipment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trk_shipment_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trk_shipment_event_shipment_id'))

    op.drop_table('trk_shipment_event')
    with op.batch_alter_table('trk_shipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trk_shipment_po_id'))

    op.drop_table('trk_shipment')
    with op.batch_alter_table('trk_purchase_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trk_purchase_order_supplier_id'))

    op.drop_table('trk_purchase_order')
    op.drop_table('trk_supplier')
    # ### end Alembic commands ###
