"""initial schema

Revision ID: c5707dc49823
Revises: 
Create Date: 2026-06-01 22:02:56.526475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5707dc49823'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_type', sa.Enum('WAREHOUSE', 'DATACENTER', 'RACK', 'SUPPLIER', 'DISPOSAL', name='locationtype'), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_code'), ['code'], unique=True)

    op.create_table('organization',
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_supplier', sa.Boolean(), nullable=False),
    sa.Column('is_manufacturer', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('product',
    sa.Column('product_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_product_code'), ['product_code'], unique=True)

    op.create_table('product_supplier',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('manufacturer_id', sa.String(length=36), nullable=True),
    sa.Column('supplier_product_code', sa.String(length=128), nullable=True),
    sa.Column('manufacturer_part_number', sa.String(length=128), nullable=True),
    sa.Column('standard_lead_time_days', sa.Integer(), nullable=True),
    sa.Column('min_order_quantity', sa.Integer(), nullable=True),
    sa.Column('contract_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('preference_rank', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_supplier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_supplier_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_supplier_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('purchase_order',
    sa.Column('order_number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'PLACED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('destination_id', sa.String(length=36), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('date_ordered', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_order_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('order_item',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('product_supplier_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('estimated_delivery_date', sa.Date(), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['product_supplier_id'], ['product_supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_item_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_product_id'), ['product_id'], unique=False)

    op.create_table('receipt',
    sa.Column('purchase_order_id', sa.String(length=36), nullable=False),
    sa.Column('received_at_id', sa.String(length=36), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['received_at_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipt_purchase_order_id'), ['purchase_order_id'], unique=False)

    op.create_table('asset',
    sa.Column('serial_number', sa.String(length=128), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'IN_STORAGE', 'DEPLOYED', 'MAINTENANCE', 'DECOMMISSIONED', 'DISPOSED', name='assetstatus'), nullable=False),
    sa.Column('current_location_id', sa.String(length=36), nullable=True),
    sa.Column('source_order_item_id', sa.String(length=36), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('deployed_date', sa.Date(), nullable=True),
    sa.Column('warranty_end_date', sa.Date(), nullable=True),
    sa.Column('decommissioned_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['source_order_item_id'], ['order_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_serial_number'), ['serial_number'], unique=True)

    op.create_table('receipt_item',
    sa.Column('receipt_id', sa.String(length=36), nullable=False),
    sa.Column('order_item_id', sa.String(length=36), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_item.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipt_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipt_item_receipt_id'), ['receipt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipt_item_receipt_id'))

    op.drop_table('receipt_item')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_serial_number'))
        batch_op.drop_index(batch_op.f('ix_asset_product_id'))

    op.drop_table('asset')
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipt_purchase_order_id'))

    op.drop_table('receipt')
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_item_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_order_id'))

    op.drop_table('order_item')
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_order_number'))

    op.drop_table('purchase_order')
    with op.batch_alter_table('product_supplier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_supplier_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_product_supplier_product_id'))

    op.drop_table('product_supplier')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_product_code'))

    op.drop_table('product')
    op.drop_table('organization')
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_code'))

    op.drop_table('location')
    # ### end Alembic commands ###
