"""add costing domain (should-cost / BOM teardown)

Revision ID: cbcfb8ce5765
Revises: a797f3c40de6
Create Date: 2026-06-07 17:50:07.914886

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cbcfb8ce5765'
down_revision: Union[str, Sequence[str], None] = 'a797f3c40de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodity',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('baseline_value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commodity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commodity_code'), ['code'], unique=True)

    op.create_table('bom',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bom', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bom_product_id'), ['product_id'], unique=True)

    op.create_table('commodity_price',
    sa.Column('commodity_id', sa.String(length=36), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commodity_price', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commodity_price_commodity_id'), ['commodity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commodity_price_price_date'), ['price_date'], unique=False)

    op.create_table('component_class',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('method', sa.Enum('teardown', 'reference_price', name='costingmethod'), nullable=False),
    sa.Column('commodity_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('component_class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_component_class_code'), ['code'], unique=True)

    op.create_table('bom_line',
    sa.Column('bom_id', sa.String(length=36), nullable=False),
    sa.Column('component_class_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('base_material_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('conversion_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('overhead_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('list_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('discount_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['bom.id'], ),
    sa.ForeignKeyConstraint(['component_class_id'], ['component_class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bom_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bom_line_bom_id'), ['bom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bom_line_component_class_id'), ['component_class_id'], unique=False)

    op.create_table('cost_params',
    sa.Column('bom_id', sa.String(length=36), nullable=False),
    sa.Column('integration_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('sga_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('target_margin_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['bom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_params', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_params_bom_id'), ['bom_id'], unique=True)

    op.create_table('should_cost_run',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('product_supplier_id', sa.String(length=36), nullable=True),
    sa.Column('should_cost_floor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('quoted_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['product_supplier_id'], ['product_supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('should_cost_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_should_cost_run_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('should_cost_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_should_cost_run_product_id'))

    op.drop_table('should_cost_run')
    with op.batch_alter_table('cost_params', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_params_bom_id'))

    op.drop_table('cost_params')
    with op.batch_alter_table('bom_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bom_line_component_class_id'))
        batch_op.drop_index(batch_op.f('ix_bom_line_bom_id'))

    op.drop_table('bom_line')
    with op.batch_alter_table('component_class', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_component_class_code'))

    op.drop_table('component_class')
    with op.batch_alter_table('commodity_price', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commodity_price_price_date'))
        batch_op.drop_index(batch_op.f('ix_commodity_price_commodity_id'))

    op.drop_table('commodity_price')
    with op.batch_alter_table('bom', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bom_product_id'))

    op.drop_table('bom')
    with op.batch_alter_table('commodity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commodity_code'))

    op.drop_table('commodity')
    # ### end Alembic commands ###
