"""add supplier onboarding fields to organization

Revision ID: db90c46c5938
Revises: e9df45c9f282
Create Date: 2026-06-08 15:59:30.122103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db90c46c5938'
down_revision: Union[str, Sequence[str], None] = 'e9df45c9f282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing suppliers (seeded / already-imported) are treated as already
    # cleared: onboarding_status defaults to 'APPROVED' and the signed-flags to
    # false-but-approved, so no existing order flow breaks. The server_default is
    # required so adding these NOT NULL columns succeeds on tables with rows.
    # New suppliers created via /suppliers/onboard are forced to DRAFT in the
    # service layer, so the gate only applies going forward.
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_status', sa.String(length=16),
                                      nullable=False, server_default='APPROVED'))
        batch_op.add_column(sa.Column('risk_level', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('risk_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('risk_assessed_at', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('dpa_signed', sa.Boolean(),
                                      nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('dpa_signed_at', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('dpa_reference', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('nda_signed', sa.Boolean(),
                                      nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('nda_signed_at', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('nda_reference', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('nda_reference')
        batch_op.drop_column('nda_signed_at')
        batch_op.drop_column('nda_signed')
        batch_op.drop_column('dpa_reference')
        batch_op.drop_column('dpa_signed_at')
        batch_op.drop_column('dpa_signed')
        batch_op.drop_column('risk_assessed_at')
        batch_op.drop_column('risk_notes')
        batch_op.drop_column('risk_level')
        batch_op.drop_column('onboarding_status')

    # ### end Alembic commands ###
