"""add external_ref + source_system for ERP/P2P integrations

Adds the (source_system, external_ref) identity pair to the three records an
upstream ERP/P2P system owns — Organization (suppliers), Product (materials),
and PurchaseOrder — so a sync from SAP/Coupa can upsert idempotently on that key
instead of duplicating rows. Both columns are nullable: records created in this
system simply leave them null. Indexed (not unique) because uniqueness is on the
*pair*, enforced at the service layer rather than by a composite DB constraint
(keeps SQLite-dev / Postgres-prod parity simple).

Revision ID: ec0024f4ffd0
Revises: c44cb7b1ba0b
Create Date: 2026-06-05 09:07:49.985504

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ec0024f4ffd0'
down_revision: Union[str, Sequence[str], None] = 'c44cb7b1ba0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_system', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('external_ref', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_organization_external_ref'), ['external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_source_system'), ['source_system'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_system', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('external_ref', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_product_external_ref'), ['external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_source_system'), ['source_system'], unique=False)

    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_system', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('external_ref', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_purchase_order_external_ref'), ['external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_source_system'), ['source_system'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_source_system'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_external_ref'))
        batch_op.drop_column('external_ref')
        batch_op.drop_column('source_system')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_source_system'))
        batch_op.drop_index(batch_op.f('ix_product_external_ref'))
        batch_op.drop_column('external_ref')
        batch_op.drop_column('source_system')

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_source_system'))
        batch_op.drop_index(batch_op.f('ix_organization_external_ref'))
        batch_op.drop_column('external_ref')
        batch_op.drop_column('source_system')

    # ### end Alembic commands ###
